name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/setup

      - run: bun run test
      - run: bun run fmt:check
      - run: bun run ts:check
      - run: bun run build

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm install --global npm@latest
      - name: Create release pull request or publish
        uses: changesets/action@v1
        with:
          publish: bun run changeset publish
          version: bun run changeset version
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
